version: '3.4'

services:
  perfectfit:
    image: perfectfit
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
